### ISSUE TITLE
pylama

### ISSUE THREAD

**Issue by ghost** [palantir/python-language-server#104]
Great work so far!

I have two small suggestion - for linter, would you consider changing pydocstyle+pyflakes to pylama? Pylama covers pretty much all the essential linters in one: pep8 (now pycodestyle), pydocstyle, pyflakes, pylint and McCabe. Easier than adding a linter for each. The recently added mypy is a nice optional addition.

I think Jedi + pylama + YAPF + isort would be a a very comprehensive combination.

**Comment by gatesn** [comment]
Thanks for the suggestions, I haven't come across Pylama before, will definitely take a look! There is already an issue open for isort #86 but we've found importmagic to have quite a lacking API. Might need to look into raw isort for that one.

**Comment by ghost** [comment]
Ah, apologies for missing isort, I edited it out from the post.

As for linters, thank a lot for considering it. Pylama is a amazing wrapper that covers all the linters of interests, including pydocstyle and pyflakes. The only thing I would suggest adding is the ability to suppress particular errors - it is available in almost any linter package in VSCode or Atom so hope it will be easy enough.

Looking forward to future releases of PLS, looks amazing!

**Comment by exploide** [comment]
Suppressing particular errors is probably a must have since this bunch of linters will probably contain a lot of less important hints, which can quickly annoy the user. This is particularly true for pylint which still aims to [get sane in version 2.0](https://github.com/PyCQA/pylint/issues/746), i.e. establishing reasonable defaults regarding less relevant hints. But since pylint seems to be more powerful than pyflakes, proposing pylint for this package once it got sane is also a thing I thought of.

Now that pylama is proposed, I'm not sure if this is a bit too much. Since it wraps several other linters, which all need to be invoked, it might be possible that this results in a performance degradation. Something probably critical for a language server, which can receive a lot of input. I must admit I haven't used pylama so far, and my concern might be groundless, but I still want to point out that this is a thing that needs to be considered before switching.

EDIT: just saw you already proposed using pylint by yourself in #62   :D

**Comment by ghost** [comment]
@exploide I have been using pylama for ages now and never notice any problem with performance (never used with a language server though).

If tests show any problems, pylama could be offer as a plugin that, when installed, disables all other linters. I for one would be OK with slight delay if it means better linting. Code quality and correctness is 
 (at least for me) much more important that a tiny delay.

FYI pylama gives a command line control over which linters will be used and an option to globally  suppress particular error types. So user can be given a choice around which linters they would prefer with default being just pycodestyle or something.

**Comment by exploide** [comment]
Ok, like I said, it might be the case that the performance drawback isn't huge. Don't know.

Good lint quality is definitely important! Ideally, one linter is simply as good as desired and afaik pylint is slightly ahead of the others. But it isn't perfect, that's true. Hopefully it will improve in the future, type checking similar to mypy and other features are planned.

What the language-server supports is up to @gatesn now. I'm fine with both, pylint, as well as a reasonably integrated pylama.

IMHO, sane defaults are always important. So having only pycodestyle and no semantical linter by default seems not a good option to me.

Beside that, I wonder why pycodestyle, pep8 and similar are necessary when using pylint. It also reports a lot of style warnings. But maybe not all, I haven't investigated this..

**Comment by ghost** [comment]
Pycodestyle is the same thing as Pep8, it is simply a newer version. There is some overlap between linters but if you satisfy one you satisfy all.

Pylint, from my experience, is not enough on its own. And its development seemed to have slowed down considerably.

With pylama you can simply switch everything else off you you like - and instead of having to support multiple linters you have one that covers everything besides optional type checking (and there is already mypy for that provided as a plugin).

I recommend you play a bit with pylama and see if you like it. To include pylint you have to install pylama_pylint.

An alternative is to have plugins for each. The main ones:
Pycodestyle (already implemented)
Pydocstyle
PyLint
PyFlakes (already implemented)
McCabe
PyChecker (haven't used so can't comment)
isort (sorts imports, with diff it shows where the imports are not sorted)

This way people can choose exact combo they like. All other I have seen (flake8, prospector etc) are wrappers around different combinations of the above.

Up to palantir to decide!

**Comment by gatesn** [comment]
I will look into how PyLama uses Pyflakes / Pycodestyle because if its similar to us, can't see a performance hit being a problem. 

The big thing for me right now is how to expose this configuration to users. I'm still unsure what the "correct" way to do this is given that it relies heavily on client support.

Solving the config issue allows us to get around the real perf issues that may arise when stacking up lots and lots of linters. Because in that case, the user can just make the tradeoff themselves between features and performance.

So probably want to punt on this decision until #57 is resolved.

The other bigger issue with PyLama is that its config sections must be of the form `[pylama:pyflakes]` not just `[pyflakes]`, meaning we expose to users that we're using pylama vs each linter individually. So that also needs to be fixed. Not sure why they made that decision..

**Comment by ghost** [comment]
Great, looking to further developments. Keep up the great work!

**Comment by ghost** [comment]
Perhaps a solution would be to make all packages (Yapf, linters etc) as plugins. Then it's a matter of installing/removing them.

**Comment by ghost** [comment]
FYI I did some testing after reading @exploide comment about performance.

Based on a rather large file, a combination of pycodestyle, pydocstyle, pyflakes and mccabe was almost instant ('pylama -l pycodestyle,pydocstyle,pyflakes,mccabe') whereas pylint (either 'pylama -l pylint' or just 'pylint') took way longer.

However, pylint was by far the best one of the the bunch and detected a lot more. It support multiprocessor option but the improvement is marginal based on my very limited testing.

Think supplying a package for each linter would be the cleanest solution as pylama is just a very convenient wrapper. If development time is limited then pylama it is by far the best option for thorough linting.

**Comment by gatesn** [comment]
Closing this in favour of individually supporting the linters. Mccabe is merged, pydocstyle is in progress, as is pylint.

**Comment by ghost** [comment]
Thanks a lot for including all!
