### ISSUE TITLE
Pylint Support

### ISSUE THREAD

**Issue by gatesn** [palantir/python-language-server#129]
In favour of PyLama #104

**Comment by ghost** [comment]
Any new development in implementing PyLint? At the end, the decision was made to provide each linter separately instead of PyLama bundle (which I personally think is a better option as it provides more flexibility). PyLint is the biggest and most thorough linter so it would be great if it was included into pyls.

Many thanks for your work on the project!

**Comment by ghost** [comment]
Any ETA for pylint? Sorry for nagging, but pylint is the biggest missing piece atm!

**Comment by DanAlbert** [comment]
There's a PR waiting for review: https://github.com/palantir/python-language-server/pull/385

**Comment by jclinton** [comment]
In the mean time, if you have lsp-ui enabled, you can add python-pylint to the checkers used by Flycheck so that python-pylint will run after the checker lsp-ui:

```lisp
(use-package lsp-ui
  :ensure t
  :after lsp-mode flycheck
  :config (setq lsp-ui-sideline-ignore-duplicate t)
          (add-hook 'lsp-mode-hook 'lsp-ui-mode)
          (flycheck-add-next-checker 'lsp-ui '(warning . python-pylint)))
```
