### ISSUE TITLE
Make rope/jedi module pre-loading configurable

### ISSUE THREAD

**Issue by gatesn** [palantir/python-language-server#179]
Right now there's a statically defined list of modules that we try to eagerly import. At the cost of memory, this can drastically reduce the time-to-first-completion.

**Comment by randy3k** [comment]
Is it the reason why the directory `.ropeproject` is still created even when `rope_completion` is not enabled?

**Comment by evandrocoan** [comment]
@randy3k, the `.ropeproject` folder currently cannot be disable by user settings because the `python-language-server` receives the settings from the language client, after loading the server plugins: https://github.com/palantir/python-language-server/pull/253#discussion_r164610715

https://github.com/palantir/python-language-server/blob/b0dc780e2e177cd1149e685e235419e0ec67841b/pyls/workspace.py#L84-L89

This way we cannot configure the plugins load options. But you can change directly your client code as the one above to pass by default `ropefolder=None`. This way the `ropeproject` folder is never created.

**Comment by gatesn** [comment]
@evandrocoan we cannot delay loading the plugins for the didChangeConfiguration message because it may never come.

Instead I've proposed this: https://github.com/palantir/python-language-server/pull/298/files

Which lazily construct a rope project, and creates a new one if the rope config changes.
