### ISSUE TITLE
Method not found: completionItem/resolve

### ISSUE THREAD

**Issue by paradoxxxzero** [palantir/python-language-server#213]
When using python-language-server with atom (atom-ide-ui 0.7.1 ide-python 0.4.0) this response is sent:
```json
{
    "error": {
        "code": -32601,
        "message": "Method not found"
    },
    "id": 3,
    "jsonrpc": "2.0"
}
```
to this request:
```json
{
    "jsonrpc": "2.0",
    "id": 3,
    "method": "completionItem/resolve",
    "params": {
        "label": "Category",
        "kind": 7,
        "detail": "__main__",
        "documentation": "",
        "sortText": "aCategory",
        "insertText": "Category"
    }
}
```
which makes the plugin stop working. I am not too sure what changed but I could work around this by adding this method in `python_ls.py`

```python
    def m_completion_item__resolve(self, completionItem=None, **_kwargs):
        return completionItem
```

**Comment by lgeiger** [comment]
Are you using Atom 1.24-beta?

It added support for computing additional info via a `completionItem/resolve` request.

`pyls` doesn't support [`completionItem/resolve` requests](https://github.com/palantir/python-language-server/blob/develop/pyls/python_ls.py#L37) since all completion details are known ahead of time.
This looks like  a bug in `atom-languageclient` since it shouldn't send `completionItem/resolve` requests to language servers that don't support them.

I don't know if delaying computation of additional info about the completion improves the performance in our case. @gatesn What do you think?

**Comment by paradoxxxzero** [comment]
Yes, sorry forgot to mention I am indeed using the 1.24-beta1.
From the look of it https://github.com/atom/atom-languageclient/pull/148 atom-languageclient ignores this setting and is at fault.
Thanks for the response.
