### ISSUE TITLE
info displayed as errors and errors displayed as info

### ISSUE THREAD

**Issue by robertocarta** [palantir/python-language-server#272]
I'm using pyls with Language Server Neovim and i get styling issues displayed as errors:
![image](https://user-images.githubusercontent.com/15035783/36640910-5cbed1f4-1a1f-11e8-8856-0b49ab4d1cc6.png)
![image](https://user-images.githubusercontent.com/15035783/36640911-63d846b4-1a1f-11e8-8bfb-6b2cd4253637.png)

and proper errors displayed as information:
![image](https://user-images.githubusercontent.com/15035783/36640925-954d2ef8-1a1f-11e8-8bff-48d49037d158.png)
![image](https://user-images.githubusercontent.com/15035783/36640926-9d26c026-1a1f-11e8-9771-da2eec2ebf01.png)

I understand that neovim gets the error type from pyls, do we have a way to fix that?
Also, I'd like to get rid of all the styling linters and only display proper errors (things that would result in a runtime error). This is very useful is old/bad codebases where the server goes crazy linting everything because of styling issues. Can pyls be configured this way?

Btw, thanks a lot for this project - it has the potential to make my life a lot easier.

**Comment by gatesn** [comment]
@robertocarta we made a change a while back so that pycodestyle diagnostics always used the Warning level: https://github.com/palantir/python-language-server/pull/124

Which version are you seeing this in?

To disable specific plugins, you can set the `pyls.plugins.<plugin_name>.enabled` configuration to `False`. See this file for all the configuration options: https://github.com/palantir/python-language-server/blob/develop/vscode-client/package.json#L78

You will need to pass those in via the language client.

**Comment by gatesn** [comment]
Fixed by #297
