### ISSUE TITLE
Ability to turn off features

### ISSUE THREAD

**Issue by wmonk** [palantir/python-language-server#286]
Hey, thanks for this plugin, it is working great! A little too great for me actually.

I am using https://github.com/autozimu/LanguageClient-neovim and want to be able to pass command line options to turn off various plugins like `pyflakes`. Is this possible currently?

**Comment by gatesn** [comment]
I'm afraid you can't configure pyflakes right now. You are able to turn it off entirely by setting `{'pyls': {'plugins': {'pyflakes': {'enabled': False}}}}` in the configuration

**Comment by nanoant** [comment]
@wmonk @gatesn That is why I have forked and made couple of changed (for my own use) here https://github.com/palantir/python-language-server/compare/develop...nanoant:patch/optional-rope-etc

Long story short it makes `rope`, `yapt` and `pydocstyle` optional, which is because:

1. Rope startup and module pre-fetch was causing serious slowdown on my Windows workstation with enterprise antivirus software (few minutes for startup - one core busy - may be related to #257) and honestly I don't see a benefit of using Rope (an additional parser and CPU/IO burden) just to have "Rename" functionality. With Jedi only and no pre-fetch, startup is instant. Btw. I think there must be a way to utilize Jedi for Rename.

2. Yapt and pydocstyle are not in `conda`, I don't want to install packages from pip, unless I install them from Git w/o dependencies, moreover I don't use/want Yapt and pydocstyle :)

IMHO, I think `jedi` should be only required dependency in PLS, rest should be completely optional. It should be most lightweight possible with its default setup.

Nevertheless, I am really happy now with (patched) PLS, I switched from Sublime Text + Anaconda to LSP plugin that handles multiple language servers. Hence @gatesn many thanks for PLS 🍺 

However, I think PLS deserves some polish, there are too many things hard-coded there (Rope Projects, pre-catched modules) and (IMHO again) too many dependencies.

@gatesn I may deliver some PR for that based on what I did in my patch if you want, but I think you have better idea how to do it right.

**Comment by gatesn** [comment]
@nanoant I completely agree with the sentiment of removing as many dependencies as possible. I've opened a ticket to track it here: https://github.com/palantir/python-language-server/issues/299

**Comment by gatesn** [comment]
@nanoant does this PR work for you? https://github.com/palantir/python-language-server/pull/301

I know it doesn't address the pre-loading of modules. I will try to address that in a separate PR.

**Comment by gatesn** [comment]
Fixed by #301

**Comment by nanoant** [comment]
@gatesn Thanks a lot for the latest changes, the only remaining problem is that `PRELOADED_MODULES` still are populated on startup even not needed, which can take a while on Windows machine, hence my additional PR #310.
