### ISSUE TITLE
Upgrade Jedi to 0.12.0

### ISSUE THREAD

**Issue by gatesn** [palantir/python-language-server#334]

**Comment by maxnordlund** [comment]
I tried turning off the version bound in my site-packages, and from my brief testing it seems fine.

**Comment by maxnordlund** [comment]
After using this for a bit more I discovered an error, https://github.com/davidhalter/jedi/commit/456ae20aacd0a8737713a92464d031297a3fce84 removed `get_venv_path` used in sys_path, see below:

https://github.com/palantir/python-language-server/blob/002982b174c8bb250b8d5b72e0d026273f66c5a8/pyls/workspace.py#L267-L278

This seems to be quite a bit of an update, which means it's not going to be easy. I hope this helps.

**Comment by gatesn** [comment]
Yup that was the issue I saw too. Although the rewrite was quite large, I imagine functionality has been preserved. Just need to find out where!

**Comment by maxnordlund** [comment]
Indeed, thanks for this lovely package BTW. I helps a lot with development.

From browsing the source trying to find that commit above, I noticed a lot of the changes are related to virtualenv support. I think that means pyls don't need to worry about it quite as much. Then trick is to use a subprocess that runs inside the virtualenv in order to access all modules etc.

Not sure about the details, but I imagine some sort of RPC over stdin to the subprocess. It looks to be seem less on the outside though.

**Comment by dryya** [comment]
Looking through the documentation, I saw that the [get_default_environment](https://jedi.readthedocs.io/en/latest/_modules/jedi/api/environment.html#get_default_environment) function has been added: removing the version bound to use jedi 0.12 and simply changing the code quoted above to `path.extend(jedi.api.environment.get_default_environment())` seemed to work for me - I hardly did any extensive testing though.

**Comment by gatesn** [comment]
I think the get_default_environment function returns an Environment object, on which a get_sys_path method exists - should call that! 

Given Jedi’s handling of environments, it does seem a little naive of us just to throw all that away. Perhaps we could make better use of it. Will file an extra ticket.

I would also note that we still need a version bound on Jedi, just the other way around.
