### ISSUE TITLE
Can't find pyls after installation on Ubuntu

### ISSUE THREAD

**Issue by unparadise** [palantir/python-language-server#338]
Hi,

I used "pip install 'python-language-server[all]'" to install pyls on my Ubuntu laptop. But after the installation finished I can't find where the pyls executable is to configure ide-python in Atom. Could you please let me know where it's installed on Ubuntu please?

Thanks,
Frank

**Comment by gatesn** [comment]
Can you enter `which pyls` and see what comes up?

**Comment by madnesspie** [comment]
> Can you enter which pyls and see what comes up?

Hi! I have a similar problem on Ubuntu 18.04 (LTS). In my case, command `which pyls` does not output anything.

**Comment by exploide** [comment]
How exactly did you install pyls (exact pip command, virtualenv?)?

What is the output of `find / -name pyls` (without possible permission denied stuff)?

**Comment by madnesspie** [comment]
> How exactly did you install pyls (exact pip command, virtualenv?)?

pip3 install 'python-language-server[all]'

> What is the output of find / -name pyls

/home/alexander/.local/lib/python3.6/site-packages/pyls
/home/alexander/.local/bin/pyls

**Comment by exploide** [comment]
Great. There it is. I'm wondering why it installed into home since you did not provide the `--user` flag to `pip3`, but anyways...

If it doesn't start when you execute `pyls` then `~/.local/bin` is probably not part of your `PATH` environment variable (check with `echo $PATH`). You have two options now:

- Just specify the full path to the executable in Atom or wherever you want to use it.
- Or you add `~/.local/bin` to your `PATH`.

I would go with the latter option. There is a lot of documentation how to do this, e.g. https://askubuntu.com/questions/60218/how-to-add-a-directory-to-the-path

**Comment by gatesn** [comment]
Closing as it seems like an issue with the PATH variable

**Comment by burkovae** [comment]
I had a similar issue using the launchpad icon in ubuntu. The problem is that applications started from launchpad only include path variables from `/etc/environment` and NOT from `.bashrc`. So either include path to python/anaconda in `/etc/environment` or modify the application start of atom-shortcut in launchpad according to https://askubuntu.com/questions/139195/how-to-include-an-environment-variable-in-the-launcher
![image](https://user-images.githubusercontent.com/15078122/42732049-e417b3f6-8819-11e8-8882-0b86b3ad963b.png)

**Comment by mangelozzi** [comment]
Ubuntu 20.04 also installed into home even though I used:
```
pip3 install python-language-server
```
Maybe because we didn't use sudo (which generally not recommended with pip).

```
which pyls
*prints nothing*
```

find / -name pyls:
```
/home/michael/.local/lib/python3.8/site-packages/pyls
/home/michael/.local/bin/pyls
```
