### ISSUE TITLE
Why some capabilities are marked as supported when they're not

### ISSUE THREAD

**Issue by AmjadHD** [palantir/python-language-server#597]
```
LSP:      {'capabilities': {'renameProvider': True, 'executeCommandProvider': {'commands': []}, 'codeActionProvider': True, 'referencesProvider': True, 'signatureHelpProvider': {'triggerCharacters': ['(', ',']}, 'definitionProvider': True, 'experimental': {}, 'documentFormattingProvider': True, 'documentHighlightProvider': True, 'textDocumentSync': 2, 'documentRangeFormattingProvider': True, 'codeLensProvider': {'resolveProvider': False}, 'completionProvider': {'resolveProvider': False, 'triggerCharacters': ['.']}, 'documentSymbolProvider': True, 'hoverProvider': True}}
```
you can see here that `codeActionProvider` and `documentHighlightProvider` are marked as supported when they are not, this makes the client (here sublime's [LSP](https://github.com/tomv564/LSP)) send Requests on every click for nothing, can you disable these untill they are actually supported ?

**Comment by gatesn** [comment]
It's not possible right now with pluggy to check if one of the pyls plugins implements the hook or not. Therefore we have to assume that we do, and return an empty result if it turns out there are no implementations of that hook.

This shouldn't cause any substantial performance issues. But if you have evidence that it does then I'd be happy to look at this more
